// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAuEb2m1IfOSuWovkk7nAnGceyaRJky-A',
    appId: '1:1062559574517:web:1baa425d790abb4ced58bc',
    messagingSenderId: '1062559574517',
    projectId: 'ds-finance-aee15',
    authDomain: 'ds-finance-aee15.firebaseapp.com',
    storageBucket: 'ds-finance-aee15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDv_isPJb-I-Wg3Hf4jDt5OP_Dvsh6Zyw',
    appId: '1:1062559574517:android:a1ef053493cee420ed58bc',
    messagingSenderId: '1062559574517',
    projectId: 'ds-finance-aee15',
    storageBucket: 'ds-finance-aee15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsYNQ7e-JgxT7UN3hqp4-MjYKKJlSEk4U',
    appId: '1:1062559574517:ios:f804557c8a664eb5ed58bc',
    messagingSenderId: '1062559574517',
    projectId: 'ds-finance-aee15',
    storageBucket: 'ds-finance-aee15.appspot.com',
    iosClientId: '1062559574517-288aifu28hlpl0p41jpdfdv6tf7lfsmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsYNQ7e-JgxT7UN3hqp4-MjYKKJlSEk4U',
    appId: '1:1062559574517:ios:e93a27b2b60049b5ed58bc',
    messagingSenderId: '1062559574517',
    projectId: 'ds-finance-aee15',
    storageBucket: 'ds-finance-aee15.appspot.com',
    iosClientId: '1062559574517-buomsb7i34574u296rbgeditbgvmkkiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaSeller.RunnerTests',
  );
}
